name: product
layer: bronze
version: "1.0.0"
description: |
  Raw product catalog data from Olist e-commerce platform.
  Contains product attributes including category and physical dimensions.
  Note: Column names have typos (lenght instead of length) - fixed in Silver.

source:
  file: olist_products_dataset.csv
  format: csv
  encoding: utf-8

columns:
  - name: product_id
    type: string
    nullable: true
    description: Unique identifier for the product
    tags: [primary_key]

  - name: product_category_name
    type: string
    nullable: true
    description: Product category in Portuguese (translated in Silver)

  - name: product_name_lenght
    type: integer
    nullable: true
    description: Length of product name in characters (typo in source)

  - name: product_description_lenght
    type: integer
    nullable: true
    description: Length of product description in characters (typo in source)

  - name: product_photos_qty
    type: integer
    nullable: true
    description: Number of product photos

  - name: product_weight_g
    type: double
    nullable: true
    description: Product weight in grams

  - name: product_length_cm
    type: double
    nullable: true
    description: Product length in centimeters

  - name: product_height_cm
    type: double
    nullable: true
    description: Product height in centimeters

  - name: product_width_cm
    type: double
    nullable: true
    description: Product width in centimeters

metadata:
  owner: data-engineering
  created_at: "2024-01-01"
  updated_at: "2024-01-05"
