name: product
layer: silver
version: "1.0.0"
description: |
  Cleaned and enriched product data.
  Category names translated from Portuguese to English.
  Column typos fixed (lenght → length).
  Physical dimensions validated to be non-negative.

source:
  table: bronze.product_raw

upstream:
  - bronze.product_raw
  - bronze.product_category_name_translation_raw

columns:
  - name: product_id
    type: string
    nullable: false
    description: Unique identifier for the product
    tags: [primary_key]

  - name: product_category_name
    type: string
    nullable: true
    description: Product category in English (translated from Portuguese)
    transform: JOIN with translation table

  - name: product_name_length
    type: integer
    nullable: true
    description: Length of product name in characters (typo fixed)

  - name: product_description_length
    type: integer
    nullable: true
    description: Length of product description in characters (typo fixed)

  - name: product_photos_qty
    type: integer
    nullable: true
    description: Number of product photos

  - name: product_weight_g
    type: double
    nullable: true
    description: Product weight in grams (validated >= 0)

  - name: product_length_cm
    type: double
    nullable: true
    description: Product length in centimeters (validated >= 0)

  - name: product_height_cm
    type: double
    nullable: true
    description: Product height in centimeters (validated >= 0)

  - name: product_width_cm
    type: double
    nullable: true
    description: Product width in centimeters (validated >= 0)

metadata:
  owner: data-engineering
  created_at: "2024-01-01"
  updated_at: "2024-01-05"
