version: 2

models:
  # --- 1. KIỂM TRA BẢNG CHIỀU (DIMENSION) ---
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          
  - name: dim_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: dim_sellers
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique

  - name: dim_datetimes
    columns:
      - name: date_id
        tests:
          - not_null
          - unique

  # --- 2. KIỂM TRA BẢNG SỰ KIỆN (FACT) ---
  - name: fct_order_items
    columns:
      - name: order_id
        tests:
          - not_null
          
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
              
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
              
      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_sellers')
              field: seller_id
              
      - name: order_date
        tests:
          - not_null
          - relationships:
              to: ref('dim_datetimes')
              field: date_id

  - name: fct_order_payments
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
              
  - name: fct_order_reviews
    columns:
      - name: review_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null

  # --- 3. CUSTOMER SEGMENTS (ML OUTPUT) ---
  - name: dim_customer_segments
    description: "Customer segments based on RFM analysis and K-Means clustering"
    columns:
      - name: customer_unique_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: recency_days
        description: "Days since last purchase"
        tests:
          - not_null
      - name: frequency
        description: "Number of orders"
        tests:
          - not_null
      - name: monetary
        description: "Total spending amount"
        tests:
          - not_null
      - name: cluster_id
        description: "Cluster ID from K-Means model"
        tests:
          - not_null
      - name: segment_name
        description: "Business-friendly segment name"
        tests:
          - not_null
          - accepted_values:
              values: ['Champions', 'Loyal Customers', 'Potential Loyalists', 'At Risk', 'Unknown']
      - name: model_version
        description: "MLflow model version used for prediction"
        tests:
          - not_null