name: 'dbt_olist'
version: '1.8.0'
config-version: 2

profile: 'dbt_olist'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Variables với default values
vars:
  catalog: olist_project
  silver_schema: silver
  gold_schema: gold

models:
  dbt_olist:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: ephemeral
    
    gold:
      +materialized: table
      +database: "{{ var('catalog') }}"


snapshots:
  dbt_olist: # (Phải khớp với 'name:')
    +target_database: "{{ var('catalog') }}"
    +target_schema: "{{ var('gold_schema') }}"