name: 'dbt_olist'
version: '1.0.0'
config-version: 2

profile: 'dbt_olist'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_olist:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: ephemeral
    
    gold:
      +materialized: table
      +database: olist_project


snapshots:
  dbt_olist: # (Phải khớp với 'name:')
    +target_database: olist_project
    +target_schema: gold